const translations = {
    en: {
        pageTitle: "Space Waves - Play Online Arcade Game",
        metaDescription: "Play Space Waves, an exciting arcade game where you control an arrow to avoid obstacles. 33 challenging levels await! Play free online now.",
        gameTitle: "Space Waves",
        playGameTitle: "Play Space Waves",
        gameDescription: "Space Waves is an arcade game where you need to control an arrow to avoid obstacles until you get to the end. There are 33 levels to the game, and you can choose any level you want to play at any time. All levels vary in difficulty and are labeled accordingly with faces; this way you get to decide how courageous you want to be.",
        gameplayVideoTitle: "Gameplay Video & Tips",
        videoDescriptionTitle: "Master the Waves",
        videoDescP1: "Watch this gameplay video to see Space Waves in action! Learn strategies for navigating tricky levels and mastering the arrow controls.",
        videoDescP2: "Pay attention to obstacle patterns and timing. Some levels require quick reflexes, while others need careful planning.",
        videoTip1: "Focus on the arrow's tip.",
        videoTip2: "Anticipate enemy movements.",
        videoTip3: "Don't be afraid to retry difficult levels.",
        relatedGamesTitle: "Related Games",
        viewGameButton: "View Game",
        controlsTitle: "Game Controls",
        controlsDesktopTitle: "Desktop",
        controlsDesktopDesc: "Move in a zigzag when obstacles are ahead, as this will give you the momentum of a straight line trajectory.",
        controlsMobileTitle: "Mobile / Gamepad",
        controlsMobileDesc: "On-screen controls or connect a gamepad for intuitive navigation.",
        faqTitle: "Frequently Asked Questions (FAQ)",
        footerText: "&copy; 2024 Space Waves Portal. All rights reserved. Game by CrazyGames."
    },
    zh: {
        pageTitle: "太空波浪 - 畅玩在线街机游戏",
        metaDescription: "畅玩太空波浪，一款刺激的街机游戏，你需要控制箭头躲避障碍物。33个富有挑战性的关卡等你来！立即免费在线畅玩。",
        gameTitle: "太空波浪",
        playGameTitle: "畅玩太空波浪",
        gameDescription: "太空波浪是一款街机游戏，您需要控制一个箭头来躲避障碍物，直到到达终点。游戏共有33个级别，您可以随时选择任何想玩的级别。所有级别的难度各不相同，并相应地用面孔标记；这样您就可以决定自己想有多勇敢。",
        gameplayVideoTitle: "游戏视频与技巧",
        videoDescriptionTitle: "掌控波浪",
        videoDescP1: "观看此游戏视频，了解太空波浪的实际操作！学习导航棘手关卡和掌握箭头控制的策略。",
        videoDescP2: "注意障碍物的模式和时机。有些关卡需要快速反应，而另一些则需要仔细规划。",
        videoTip1: "专注于箭头的尖端。",
        videoTip2: "预测敌人的动向。",
        videoTip3: "不要害怕重试困难的关卡。",
        relatedGamesTitle: "相关游戏",
        viewGameButton: "查看游戏",
        controlsTitle: "游戏操作",
        controlsDesktopTitle: "电脑端",
        controlsDesktopDesc: "当前方有障碍物时，以之字形移动，因为这会给你一条直线轨迹的动量。",
        controlsMobileTitle: "移动端 / 游戏手柄",
        controlsMobileDesc: "使用屏幕上的控件或连接游戏手柄进行直观导航。",
        faqTitle: "常见问题解答 (FAQ)",
        footerText: "&copy; 2025 太空波浪门户网站。版权所有。"
    },
    es: {
        pageTitle: "Space Waves - Juega Juego Arcade Online",
        metaDescription: "Juega Space Waves, un emocionante juego arcade donde controlas una flecha para evitar obstáculos. ¡Te esperan 33 desafiantes niveles! Juega gratis online ahora.",
        gameTitle: "Space Waves",
        playGameTitle: "Jugar Space Waves",
        gameDescription: "Space Waves es un juego arcade en el que necesitas controlar una flecha para evitar obstáculos hasta llegar al final. Hay 33 niveles en el juego, y puedes elegir cualquier nivel que quieras jugar en cualquier momento. Todos los niveles varían en dificultad y están etiquetados correspondientemente con caras; de esta manera puedes decidir cuán valiente quieres ser.",
        gameplayVideoTitle: "Video de Jugabilidad y Consejos",
        videoDescriptionTitle: "Domina las Olas",
        videoDescP1: "¡Mira este video de jugabilidad para ver Space Waves en acción! Aprende estrategias para navegar niveles complicados y dominar los controles de la flecha.",
        videoDescP2: "Presta atención a los patrones de obstáculos y al tiempo. Algunos niveles requieren reflejos rápidos, mientras que otros necesitan una planificación cuidadosa.",
        videoTip1: "Concéntrate en la punta de la flecha.",
        videoTip2: "Anticipa los movimientos enemigos.",
        videoTip3: "No temas reintentar niveles difíciles.",
        relatedGamesTitle: "Juegos Relacionados",
        viewGameButton: "Ver Juego",
        controlsTitle: "Controles del Juego",
        controlsDesktopTitle: "Escritorio",
        controlsDesktopDesc: "Move in a zigzag when obstacles are ahead, as this will give you the momentum of a straight line trajectory.",
        controlsMobileTitle: "Móvil / Gamepad",
        controlsMobileDesc: "Controles en pantalla o conecta un gamepad para una navegación intuitiva.",
        faqTitle: "Preguntas Frecuentes (FAQ)",
        footerText: "&copy; 2025 Portal de Space Waves. "
    }
    // Add more languages as needed
};
